#!/usr/bin/python3

from sys import argv

def factorize(x):
    y = 2

    if x < 2:
        return
    
    while x % y:
        y += 1
    print("{:.0f}={:.0f}*{:.0f}".format(x, x / y, y))

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            x = int(line.split('\n')[0])
            factorize(x)
            line = file.readline()
except:
    pass
